name:                pacchettibotti
version:             0.1.0
github:              "spacchetti/pacchettibotti"
license:             AGPL-3
author:              "Fabrizio Ferrai"
maintainer:          "@fabferrai"
copyright:           "2020 Fabrizio Ferrai"

extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

description:         Please see the README on GitHub at <https://github.com/spacchetti/pacchettibotti>

default-extensions:
- AutoDeriveTypeable
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadFailDesugaring
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeSynonymInstances
- ViewPatterns

library:
  source-dirs: src
  dependencies:
  - aeson
  - aeson-pretty
  - async
  - async-pool
  - base >= 4.7 && < 5
  - bower-json
  - bytestring
  - conduit
  - conduit-extra
  - containers
  - dhall
  - filelock
  - filepath
  - generic-lens
  - github
  - Glob
  - http-api-data
  - http-client
  - http-client-tls
  - http-conduit
  - language-javascript
  - megaparsec
  - network-uri
  - path-pieces
  - persistent
  - persistent-sqlite
  - persistent-template
  - process
  - retry
  - rio
  - rio-orphans
  - semver-range
  - spago
  - stm
  - tar-conduit
  - temporary
  - text < 1.3
  - time
  - turtle
  - unliftio
  - vector

executables:
  pacchettibotti:
    main:                PacchettiBotti.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -main-is PacchettiBotti
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - base >= 4.7 && < 5
    - containers
    - http-conduit
    - pacchettibotti
    - stm
    - text < 1.3
